### ISSUE TITLE
update travis messaging

### ISSUE THREAD

**Issue by n8rzz** [openscope/openscope#503]
https://docs.travis-ci.com/user/notifications/#Configuring-slack-notifications

```yaml
notifications:
  slack:
    template:
      - "Build %{result} in %{duration} - %{branch} by %{author}"
      - "<%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>)"
      - "%{commit_message}"
```
